#!/usr/bin/env python3
"""
WhatsApp NLP Project - Advanced Error Analysis

This script provides detailed error analysis for the evaluation results,
including confidence analysis, message patterns, and error categorization.

Usage: python evaluate/error_analysis.py

Note: Run evaluate.py first to generate the necessary error CSV files.
"""

import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

class ErrorAnalyzer:
    """Advanced error analysis for WhatsApp NLP evaluation results."""
    
    def __init__(self, results_dir="evaluate/results"):
        self.results_dir = results_dir
        self.sentiment_errors = None
        self.sarcasm_errors = None
        self.combined_errors = None
        
        print("WhatsApp NLP Error Analyzer initialized")
        print(f"Results directory: {results_dir}")
    
    def load_error_data(self):
        """Load error CSV files generated by the main evaluation."""
        print("\n" + "="*50)
        print("LOADING ERROR DATA")
        print("="*50)
        
        # Load sentiment errors
        sent_error_path = f"{self.results_dir}/sentiment/sentiment_errors.csv"
        if os.path.exists(sent_error_path):
            self.sentiment_errors = pd.read_csv(sent_error_path)
            print(f"Loaded {len(self.sentiment_errors):,} sentiment errors")
        else:
            print("No sentiment errors file found")
            
        # Load sarcasm errors
        sarc_error_path = f"{self.results_dir}/sarcasm/sarcasm_errors.csv"
        if os.path.exists(sarc_error_path):
            self.sarcasm_errors = pd.read_csv(sarc_error_path)
            print(f"Loaded {len(self.sarcasm_errors):,} sarcasm errors")
        else:
            print("No sarcasm errors file found")
            
        # Load combined errors
        comb_error_path = f"{self.results_dir}/combined/combined_errors.csv"
        if os.path.exists(comb_error_path):
            self.combined_errors = pd.read_csv(comb_error_path)
            print(f"Loaded {len(self.combined_errors):,} combined errors")
        else:
            print("No combined errors file found")
    
    def analyze_sentiment_error_patterns(self):
        """Analyze patterns in sentiment prediction errors."""
        if self.sentiment_errors is None or len(self.sentiment_errors) == 0:
            print("\nNo sentiment errors to analyze")
            return
            
        print("\n" + "="*50)
        print("SENTIMENT ERROR PATTERN ANALYSIS")
        print("="*50)
        
        # Error transition patterns (actual -> predicted)
        error_patterns = []
        for _, row in self.sentiment_errors.iterrows():
            pattern = f"{row['actual_sentiment']} → {row['predicted_sentiment']}"
            error_patterns.append(pattern)
        
        pattern_counts = Counter(error_patterns)
        print("Most common sentiment error patterns:")
        for pattern, count in pattern_counts.most_common():
            pct = count / len(self.sentiment_errors) * 100
            print(f"  {pattern}: {count:,} ({pct:.1f}%)")
        
        # Confidence score analysis
        if 'sentiment_confidence' in self.sentiment_errors.columns:
            print(f"\nSentiment confidence analysis for errors:")
            conf_scores = self.sentiment_errors['sentiment_confidence']
            print(f"  Mean confidence: {conf_scores.mean():.4f}")
            print(f"  Median confidence: {conf_scores.median():.4f}")
            print(f"  Std deviation: {conf_scores.std():.4f}")
            print(f"  Min confidence: {conf_scores.min():.4f}")
            print(f"  Max confidence: {conf_scores.max():.4f}")
            
            # Low confidence errors (model was uncertain)
            low_conf_threshold = 0.6
            low_conf_errors = self.sentiment_errors[conf_scores < low_conf_threshold]
            print(f"  Errors with confidence < {low_conf_threshold}: {len(low_conf_errors):,} "
                  f"({len(low_conf_errors)/len(self.sentiment_errors)*100:.1f}%)")
        
        # Message length analysis
        self.sentiment_errors['message_length'] = self.sentiment_errors['message'].str.len()
        print(f"\nMessage length analysis for sentiment errors:")
        lengths = self.sentiment_errors['message_length']
        print(f"  Mean length: {lengths.mean():.1f} characters")
        print(f"  Median length: {lengths.median():.1f} characters")
        print(f"  Std deviation: {lengths.std():.1f} characters")
        
        # Show examples of each error pattern
        print(f"\nExample messages for top error patterns:")
        for pattern, count in pattern_counts.most_common(3):
            pattern_examples = self.sentiment_errors[
                (self.sentiment_errors['actual_sentiment'] + ' → ' + 
                 self.sentiment_errors['predicted_sentiment']) == pattern
            ]
            
            print(f"\n  {pattern} ({count} cases):")
            for _, example in pattern_examples.head(3).iterrows():
                msg = example['message']
                if len(msg) > 80:
                    msg = msg[:80] + "..."
                conf = example.get('sentiment_confidence', 'N/A')
                print(f"    [{conf}] \"{msg}\"")
    
    def analyze_sarcasm_error_patterns(self):
        """Analyze patterns in sarcasm prediction errors."""
        if self.sarcasm_errors is None or len(self.sarcasm_errors) == 0:
            print("\nNo sarcasm errors to analyze")
            return
            
        print("\n" + "="*50)
        print("SARCASM ERROR PATTERN ANALYSIS")
        print("="*50)
        
        # False positives vs false negatives
        false_positives = self.sarcasm_errors[
            (self.sarcasm_errors['actual_sarcasm'] == False) & 
            (self.sarcasm_errors['predicted_sarcasm'] == True)
        ]
        false_negatives = self.sarcasm_errors[
            (self.sarcasm_errors['actual_sarcasm'] == True) & 
            (self.sarcasm_errors['predicted_sarcasm'] == False)
        ]
        
        print(f"Sarcasm error breakdown:")
        print(f"  False Positives (predicted sarcastic, actually not): {len(false_positives):,}")
        print(f"  False Negatives (predicted not sarcastic, actually sarcastic): {len(false_negatives):,}")
        
        # Confidence analysis
        if 'sarcasm_confidence' in self.sarcasm_errors.columns:
            print(f"\nSarcasm confidence analysis for errors:")
            conf_scores = self.sarcasm_errors['sarcasm_confidence']
            print(f"  Mean confidence: {conf_scores.mean():.4f}")
            print(f"  Median confidence: {conf_scores.median():.4f}")
            print(f"  Std deviation: {conf_scores.std():.4f}")
            
            # Analyze confidence by error type
            if len(false_positives) > 0:
                fp_conf = false_positives['sarcasm_confidence']
                print(f"  False Positive mean confidence: {fp_conf.mean():.4f}")
            
            if len(false_negatives) > 0:
                fn_conf = false_negatives['sarcasm_confidence']
                print(f"  False Negative mean confidence: {fn_conf.mean():.4f}")
        
        # Message length analysis
        self.sarcasm_errors['message_length'] = self.sarcasm_errors['message'].str.len()
        lengths = self.sarcasm_errors['message_length']
        print(f"\nMessage length analysis for sarcasm errors:")
        print(f"  Mean length: {lengths.mean():.1f} characters")
        print(f"  Median length: {lengths.median():.1f} characters")
        
        # Show examples
        print(f"\nExample False Positive errors (predicted sarcastic, actually not):")
        if len(false_positives) > 0:
            for _, example in false_positives.head(5).iterrows():
                msg = example['message']
                if len(msg) > 80:
                    msg = msg[:80] + "..."
                conf = example.get('sarcasm_confidence', 'N/A')
                print(f"  [{conf}] \"{msg}\"")
        else:
            print("  None")
        
        print(f"\nExample False Negative errors (predicted not sarcastic, actually sarcastic):")
        if len(false_negatives) > 0:
            for _, example in false_negatives.head(5).iterrows():
                msg = example['message']
                if len(msg) > 80:
                    msg = msg[:80] + "..."
                conf = example.get('sarcasm_confidence', 'N/A')
                print(f"  [{conf}] \"{msg}\"")
        else:
            print("  None")
    
    def analyze_combined_error_interactions(self):
        """Analyze how sentiment and sarcasm errors interact."""
        if self.combined_errors is None or len(self.combined_errors) == 0:
            print("\nNo combined errors to analyze")
            return
            
        print("\n" + "="*50)
        print("COMBINED ERROR INTERACTION ANALYSIS")
        print("="*50)
        
        # Categorize error types
        both_wrong = self.combined_errors[
            (self.combined_errors['actual_sentiment'] != self.combined_errors['predicted_sentiment']) &
            (self.combined_errors['actual_sarcasm'] != self.combined_errors['predicted_sarcasm'])
        ]
        
        only_sentiment_wrong = self.combined_errors[
            (self.combined_errors['actual_sentiment'] != self.combined_errors['predicted_sentiment']) &
            (self.combined_errors['actual_sarcasm'] == self.combined_errors['predicted_sarcasm'])
        ]
        
        only_sarcasm_wrong = self.combined_errors[
            (self.combined_errors['actual_sentiment'] == self.combined_errors['predicted_sentiment']) &
            (self.combined_errors['actual_sarcasm'] != self.combined_errors['predicted_sarcasm'])
        ]
        
        print(f"Error interaction patterns:")
        print(f"  Both models wrong: {len(both_wrong):,}")
        print(f"  Only sentiment wrong: {len(only_sentiment_wrong):,}")
        print(f"  Only sarcasm wrong: {len(only_sarcasm_wrong):,}")
        
        # Analyze correlation between errors
        if len(both_wrong) > 0:
            print(f"\nMessages where BOTH models failed:")
            for _, example in both_wrong.head(3).iterrows():
                msg = example['message']
                if len(msg) > 100:
                    msg = msg[:100] + "..."
                print(f"  Message: \"{msg}\"")
                print(f"    Sentiment: {example['actual_sentiment']} → {example['predicted_sentiment']}")
                print(f"    Sarcasm: {example['actual_sarcasm']} → {example['predicted_sarcasm']}")
                print()
    
    def create_error_visualizations(self):
        """Create visualizations of error patterns."""
        print("\n" + "="*50)
        print("CREATING ERROR VISUALIZATIONS")
        print("="*50)
        
        # Sentiment error confidence distribution
        if (self.sentiment_errors is not None and 
            len(self.sentiment_errors) > 0 and 
            'sentiment_confidence' in self.sentiment_errors.columns):
            
            plt.figure(figsize=(10, 6))
            plt.hist(self.sentiment_errors['sentiment_confidence'], bins=20, 
                    alpha=0.7, color='blue', edgecolor='black')
            plt.xlabel('Confidence Score')
            plt.ylabel('Number of Errors')
            plt.title('Distribution of Confidence Scores for Sentiment Errors')
            plt.axvline(self.sentiment_errors['sentiment_confidence'].mean(), 
                       color='red', linestyle='--', 
                       label=f'Mean: {self.sentiment_errors["sentiment_confidence"].mean():.3f}')
            plt.legend()
            plt.tight_layout()
            
            save_path = f"{self.results_dir}/sentiment/error_confidence_distribution.png"
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            plt.close()
            print(f"Sentiment error confidence distribution saved: {save_path}")
        
        # Sarcasm error confidence distribution
        if (self.sarcasm_errors is not None and 
            len(self.sarcasm_errors) > 0 and 
            'sarcasm_confidence' in self.sarcasm_errors.columns):
            
            plt.figure(figsize=(10, 6))
            plt.hist(self.sarcasm_errors['sarcasm_confidence'], bins=20,
                    alpha=0.7, color='red', edgecolor='black')
            plt.xlabel('Confidence Score')
            plt.ylabel('Number of Errors')
            plt.title('Distribution of Confidence Scores for Sarcasm Errors')
            plt.axvline(self.sarcasm_errors['sarcasm_confidence'].mean(),
                       color='blue', linestyle='--',
                       label=f'Mean: {self.sarcasm_errors["sarcasm_confidence"].mean():.3f}')
            plt.legend()
            plt.tight_layout()
            
            save_path = f"{self.results_dir}/sarcasm/error_confidence_distribution.png"
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            plt.close()
            print(f"Sarcasm error confidence distribution saved: {save_path}")
        
        # Message length vs confidence scatter plot for sentiment errors
        if (self.sentiment_errors is not None and 
            len(self.sentiment_errors) > 0 and 
            'sentiment_confidence' in self.sentiment_errors.columns and
            'message_length' in self.sentiment_errors.columns):
            
            plt.figure(figsize=(10, 6))
            plt.scatter(self.sentiment_errors['message_length'],
                       self.sentiment_errors['sentiment_confidence'],
                       alpha=0.6, color='blue')
            plt.xlabel('Message Length (characters)')
            plt.ylabel('Confidence Score')
            plt.title('Message Length vs Confidence Score for Sentiment Errors')
            plt.tight_layout()
            
            save_path = f"{self.results_dir}/sentiment/length_vs_confidence_errors.png"
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            plt.close()
            print(f"Sentiment length vs confidence plot saved: {save_path}")
    
    def generate_error_report(self):
        """Generate comprehensive error analysis report."""
        print("\n" + "="*50)
        print("GENERATING ERROR ANALYSIS REPORT")
        print("="*50)
        
        report_lines = []
        report_lines.append("WhatsApp NLP - Advanced Error Analysis Report")
        report_lines.append("="*60)
        report_lines.append(f"Generated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report_lines.append("")
        
        # Sentiment error analysis
        if self.sentiment_errors is not None and len(self.sentiment_errors) > 0:
            report_lines.append("SENTIMENT ERROR ANALYSIS:")
            report_lines.append(f"  Total sentiment errors: {len(self.sentiment_errors):,}")
            
            if 'sentiment_confidence' in self.sentiment_errors.columns:
                conf_mean = self.sentiment_errors['sentiment_confidence'].mean()
                conf_std = self.sentiment_errors['sentiment_confidence'].std()
                report_lines.append(f"  Mean error confidence: {conf_mean:.4f} (±{conf_std:.4f})")
            
            if 'message_length' in self.sentiment_errors.columns:
                length_mean = self.sentiment_errors['message_length'].mean()
                report_lines.append(f"  Mean error message length: {length_mean:.1f} characters")
            
            report_lines.append("")
        
        # Sarcasm error analysis
        if self.sarcasm_errors is not None and len(self.sarcasm_errors) > 0:
            report_lines.append("SARCASM ERROR ANALYSIS:")
            report_lines.append(f"  Total sarcasm errors: {len(self.sarcasm_errors):,}")
            
            # False positive/negative breakdown
            false_positives = self.sarcasm_errors[
                (self.sarcasm_errors['actual_sarcasm'] == False) & 
                (self.sarcasm_errors['predicted_sarcasm'] == True)
            ]
            false_negatives = self.sarcasm_errors[
                (self.sarcasm_errors['actual_sarcasm'] == True) & 
                (self.sarcasm_errors['predicted_sarcasm'] == False)
            ]
            
            report_lines.append(f"  False positives: {len(false_positives):,}")
            report_lines.append(f"  False negatives: {len(false_negatives):,}")
            
            if 'sarcasm_confidence' in self.sarcasm_errors.columns:
                conf_mean = self.sarcasm_errors['sarcasm_confidence'].mean()
                conf_std = self.sarcasm_errors['sarcasm_confidence'].std()
                report_lines.append(f"  Mean error confidence: {conf_mean:.4f} (±{conf_std:.4f})")
            
            report_lines.append("")
        
        # Combined analysis
        if self.combined_errors is not None and len(self.combined_errors) > 0:
            both_wrong = self.combined_errors[
                (self.combined_errors['actual_sentiment'] != self.combined_errors['predicted_sentiment']) &
                (self.combined_errors['actual_sarcasm'] != self.combined_errors['predicted_sarcasm'])
            ]
            
            report_lines.append("COMBINED ERROR ANALYSIS:")
            report_lines.append(f"  Total messages with any error: {len(self.combined_errors):,}")
            report_lines.append(f"  Messages with both errors: {len(both_wrong):,}")
            report_lines.append("")
        
        # Save report
        report_text = "\n".join(report_lines)
        report_file = f"{self.results_dir}/reports/error_analysis_report.txt"
        
        with open(report_file, "w", encoding='utf-8') as f:
            f.write(report_text)
        
        print(f"Error analysis report saved: {report_file}")
    
    def run_complete_error_analysis(self):
        """Execute complete error analysis pipeline."""
        print("WhatsApp NLP - Advanced Error Analysis")
        print("="*50)
        
        try:
            self.load_error_data()
            self.analyze_sentiment_error_patterns()
            self.analyze_sarcasm_error_patterns()
            self.analyze_combined_error_interactions()
            self.create_error_visualizations()
            self.generate_error_report()
            
            print("\n" + "="*50)
            print("ERROR ANALYSIS COMPLETED SUCCESSFULLY!")
            print("="*50)
            
        except Exception as e:
            print(f"\nERROR during analysis: {e}")
            raise


def main():
    """Main execution function."""
    analyzer = ErrorAnalyzer()
    analyzer.run_complete_error_analysis()


if __name__ == "__main__":
    main()